services:
  app:
    container_name: excelinsightFe
    build:
      context: .
      dockerfile: Dockerfiledev # Ensure you name your development Dockerfile as 'Dockerfile.dev'
    ports:
      - "3000:3000"
    volumes:
      - .:/app # Mounts the current directory to the container for live code changes
      - /app/node_modules # Ensures node_modules from the container are isolated
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
